### ISSUE TITLE
app script fails

### ISSUE THREAD

**Issue by jochenpee** [wez3/volkswagen-carnet-client#11]
This is what I get, I don't understand it. The web script works, but not the app:

~# vw_carnet_app.py retrieveCarNetInfo
Logging in
token: cQr4U8sq+CdEflnlgobh/xeehlyuElpcs0pHGuGoS2ZHZ5vteiAa
Retrieving verhicle
Retrieving CarNetInfo
Traceback (most recent call last):
  File "/usr/local/bin/vw_carnet_app.py", line 178, in <module>
    retrieveCarNetInfo(VIN)
  File "/usr/local/bin/vw_carnet_app.py", line 84, in retrieveCarNetInfo
    climateHeatingWindowFrontStatus = responseData.get("climater").get("status").get("windowHeatingStatusData").get("windowHeatingStateFront").get("content")
AttributeError: 'NoneType' object has no attribute 'get'

**Comment by mikaelho** [comment]
Still works normally for me.
