### ISSUE TITLE
Car Service

### ISSUE THREAD

**Issue by 0rsa** [wez3/volkswagen-carnet-client#13]
Hello,

First, thank you for your work, it's very convenient for my use.
Service values (serviceInKm & serviceInDays) are empty in my case, values are correct using Car Net website.
Can you check?

Thank you.

**Comment by mikaelho** [comment]
Looks like there is a missing conversion to int before multiplying with -1.

**Comment by 0rsa** [comment]
You're right, I removed line which multiply by -1 and the value is now showed up.
Thank you.
