### ISSUE TITLE
API Changes (April 2019)

### ISSUE THREAD

**Issue by uberboffin** [wez3/volkswagen-carnet-client#15]
It appears that VW are making some changes to their APIs today (OAuth?) and I wonder what this will mean for the *excellent* library? Their system is down at the moment, so time will tell.

**Comment by mikaelho** [comment]
My client seems to be still working, and it uses both the ”API” and ”web” versions of the code here. Thus I would say that they did not make any breaking changes.

![e-Golf dashboard](https://raw.githubusercontent.com/mikaelho/pythonista-uiconstraints/master/images/gridview-sample.jpeg)
