### ISSUE TITLE
API (auth) change

### ISSUE THREAD

**Issue by Maverick78de** [wez3/volkswagen-carnet-client#16]
It seems VW changed the API or authentication today (2019/07/08) . Script doesn't work anymore. :(

**Comment by mikaelho** [comment]
Confirm, not working here either. Neither the API or the web scraping version.

**Comment by Chris383838** [comment]
For me the same dosent work.

**Comment by Cloud217** [comment]
Same problem here

**Comment by Cloud217** [comment]
The mobile app for iphone had been updated to "We Connect".  I think they have been migrating the application to a new platform hence a new api?

**Comment by jochenpee** [comment]
Yes, app and API have changed. An update to this script would be terrific! I am not able to do it myself.

**Comment by birgersp** [comment]
This leaves my own implementation currently useless. Really hoping someone can find out if and how clients can communicate with the new VW implementation. I would love to help out in any way I can but I'm afraid I'm underqualified in this regard.

**Comment by wez3** [comment]
I don't have the car and the app anymore, so cannot update the scripts. sorry guys! :-(

**Comment by birgersp** [comment]
No hard feelings :)
FYI there's also people trying to find a solution here:
https://github.com/reneboer/python-carnet-client/issues/5

**Comment by vomov** [comment]
> I don't have the car and the app anymore, so cannot update the scripts. sorry guys! :-(
Would it perhaps then be helpful to state that this won't be updated anymore in the readme?

**Comment by Maverick78de** [comment]
> I don't have the car and the app anymore, so cannot update the scripts. sorry guys! :-(

@wez3 would it help if I give you access to a car?

**Comment by youpixel** [comment]
Guys,

yesterday a new change was made to the login portal. 
I revisited the script of reneboer and made some changes to it.

https://github.com/reneboer/python-carnet-client/issues/5#issuecomment-515466366

Cheers,

youpixel aka rehlus ;-)

**Comment by jochenpee** [comment]
Dear @bgewehr, since Dec 18th I get: 
Failed to login Failed to get portlet code.
Can you fix it?
Thanks!

**Comment by birgersp** [comment]
Facing the same issue. I've reported it to the reneboer/python-carnet-client#30. I think that repository is more active than this one.

**Comment by bgewehr** [comment]
I had to repeat my grants on manual web login, since then the script worked again. Give it a try!

**Comment by jochenpee** [comment]
Yes, it works! Thanks a lot!

**Comment by Chris383838** [comment]
Hi, can you please exact explain how fix the problem? I have the same issue.

**Comment by bgewehr** [comment]
Do a manual login in the VW we web portal. I was asked to grant the access scopes during the openID login procedure - and after that the script did work again like before.

**Comment by birgersp** [comment]
Works for me! Go to the official We Connect website and log in to your account there. A huge relief for me, thanks!

**Comment by birgersp** [comment]
(This issue should be closed)
