### ISSUE TITLE
Problems with certain characters?

### ISSUE THREAD

**Issue by yeniklas** [wez3/volkswagen-carnet-client#3]
When running retrieveCarNetInfo this is what I get. It might be due to the fact that my car-net is in Swedish? I have not been able to confirm this since I can't change the language.

```
Logging in
Retrieving verhicle
Retrieving CarNetInfo
Traceback (most recent call last):
  File "vw_carnet.py", line 108, in <module>
    retrieveCarNetInfo(VIN)
  File "vw_carnet.py", line 64, in retrieveCarNetInfo
    print str(loc)
UnicodeEncodeError: 'ascii' codec can't encode character u'\xe4' in position 8: ordinal not in range(128)
```

**Comment by wez3** [comment]
Strange. It might be some swedish characters. Maybe you can try to remove the str() on line 64. That might work.

**Comment by cschriel** [comment]
\xe4 translates to 'ä'. That character is probably somewhere in the location of your vehicle, i.e. streetname.

**Comment by yeniklas** [comment]
@wez3 Yeah you were right, I changed it into this "print "Location %s" % loc" instead and it works fine.

**Comment by wez3** [comment]
Great!
