### ISSUE TITLE
endpoint to trips

### ISSUE THREAD

**Issue by larsmeldgaard** [wez3/volkswagen-carnet-client#6]
Hi guys - great work. Any change of finding the endpoints for the trips history and current battery level?
I a range is provides somewhere in StoredVehicleData, but that's the calculated range. Don't the car store percentage of battery (to draw the battery-graph in the app)

**Comment by wez3** [comment]
The new version retrieves the batteryPercentage:
https://github.com/wez3/volkswagen-carnet-client/blob/master/vw_carnet_web.py

**Comment by larsmeldgaard** [comment]
This works perfectly. Your web version provides the data neccessary. Just missing the trips now
