### ISSUE TITLE
Works fine for France

### ISSUE THREAD

**Issue by borisgodet** [wez3/volkswagen-carnet-client#8]
Amazing ... 
Then I use https://maps.googleapis.com/maps/api/geocode/xml?latlng=48.85837,2.294481 to retrieve the address from my Golf GTE GPS coordinates, and TTS + stream2chromecast to have my Google Assistant answering me where the car is located.
Great ! Thanks.

**Comment by wez3** [comment]
Great to hear! Nice implementation btw :) 👍
